#include "visualLB.h"
#include <stdio.h>
#include "LBDefinitions.h"
#include "helper.h"
#include "computeCellValues.h"

void writeVtkOutput(const double * const collideField, const int * const flagField,
        const char * filename, int rank, int iproc, int jproc, int kproc, unsigned int t, const int * const sublength)
{
    /* TODO: Replace by arb. geometry version */
    char fn[80];
    /* Save filename as a combination of passed filename and timestep */
    sprintf(fn, "%s_%d.%d.%d.%i.vtk", filename, rank%iproc, rank/iproc%jproc, rank/(iproc*jproc), t);

    FILE *fp = fopen(fn, "w");
    if (fp == NULL) {
        ERROR("Failed to open file!");
        return;
    }

    fprintf(fp, "# vtk DataFile Version 2.0\n");
    fprintf(fp, "generated by CFD-lab course output \n");
    fprintf(fp, "ASCII\n\n");
    fprintf(fp, "DATASET STRUCTURED_GRID\n");
    fprintf(fp, "DIMENSIONS %d %d %d \n", sublength[0] + 1, sublength[1] + 1, sublength[2] + 1);
    fprintf(fp, "POINTS %d float\n\n",
            (sublength[0] + 1) * (sublength[1] + 1) * (sublength[2] + 1));

    /* Print lattice points */
    for (int z = 1; z < sublength[2] + 2; ++z) {
        for (int y = 1; y < sublength[1] + 2; ++y) {
            for (int x = 1; x < sublength[0] + 2; ++x) {
                fprintf(fp, "%d %d %d\n", x, y, z);
            }
        }
    }

    fprintf(fp, "POINT_DATA %d \n\n", (sublength[0] + 1) * (sublength[1] + 1) * (sublength[2] + 1));
    fprintf(fp, "VECTORS velocity float\n");

    double density;
    double vel[D];
    const double *currentCell;
    /* Compute (macroscopic) velocities for all cells */
    for (int z = 1; z < sublength[2] + 2; ++z) {
        for (int y = 1; y < sublength[1] + 2; ++y) {
            for (int x = 1; x < sublength[0] + 2; ++x) {
                currentCell = &collideField[idx(sublength, x, y, z, 0)];
                computeDensity(currentCell, &density);
                computeVelocity(currentCell, &density, vel);
                fprintf(fp, "%f %f %f\n", vel[0], vel[1], vel[2]);
            }
        }
    }

    fprintf(fp, "\nCELL_DATA %d \n", (sublength[0]) * (sublength[1]) * (sublength[2]));
    fprintf(fp, "SCALARS density float 1 \n");
    fprintf(fp, "LOOKUP_TABLE default \n");

    /* Compute density for each cell */
    for (int z = 1; z < sublength[2] + 1; ++z) {
        for (int y = 1; y < sublength[1] + 1; ++y) {
            for (int x = 1; x < sublength[0] + 1; ++x) {
                currentCell = &collideField[idx(sublength, x, y, z, 0)];
                computeDensity(currentCell, &density);
                fprintf(fp, "%f\n", density);
            }
        }
    }

    if (fclose(fp)) {
        ERROR("Failed to close file!");
        return;
    }
}

